name: Benchmark

on:
  workflow_dispatch:
    inputs:
      cleanup:
        description: "Fresh start?"
        type: boolean
        required: true
        default: false

permissions:
  contents: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: "Cleanup"
        if: ${{ inputs.cleanup }}
        run: |
          rm -rf ./data/processedVersions.json
          echo "{}" > ./data/processedVersions.json

      - name: "Package Versions"
        run: |
          docker --version
          node --version
          yarn --version

      - name: "Install Dependencies"
        run: "yarn"

      - name: "Run Benchmark"
        run: "yarn start"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload Benchmark Results"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Benchmark Data"
          git push
